GET http://localhost:3000/api/articles

###

GET http://localhost:3000/api/articles/4uSmm9uF9PHoElJYJjXxL

###

GET http://localhost:3000/api/categories

###

POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 ",
  "image": "image.png",
  "createdDate": "2021-07-19T13:42:40.784Z",
  "category": ["Деревья", "sdf"],
  "announce": "new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 new post 1 ",
  "fullText": "new post"
}

###

PUT http://localhost:3000/api/articles/zHN1eqzlKQsIuUo4ey9_x
Content-Type: application/json

{
  "title": "ksfjvkjv ksfjvkjv ksfjvkjvvмv ksfjvkjvksfjvkjvksfjvkjvksfjvkjv ksfjvkjv ksfjvkjvksfjvkjvksfjvkjv   иksfjvkjvksfjvkjv v ksfjvkjv"
}

###

DELETE http://localhost:3000/api/articles/XSGXUNY1v_-wKYV5ssWeY

###

GET http://localhost:3000/api/articles/sdziY3YYdq25E1-B7gebT/comments

###

DELETE http://localhost:3000/api/articles/sdziY3YYdq25E1-B7gebT/comments/t5tFCjqCZJY9QKljfVbDU

###

POST http://localhost:3000/api/articles/zHN1eqzlKQsIuUo4ey9_x/comments
Content-Type: application/json

{
  "text": "edbnvdflknvfkn edbnvdflknvfknedbnvdflknvfkn edbnvdflknvfkn edbnvdflknvfkn v v edbnvdflknvfkn edbnvdflknvfknedbnvdflknvfkn"
}

###

GET http://localhost:3000/api/search?query=перестать
